"""
Django settings for nuam_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Inicializar environ
env = environ.Env(
    # Valores por defecto
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Leer archivo .env
environ.Env.read_env(BASE_DIR / '.env')

# Configuración de inicio rápido para desarrollo - no apta para producción
# Ver https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: mantener la clave secreta protegida en producción
SECRET_KEY = env('SECRET_KEY')

# ADVERTENCIA DE SEGURIDAD: no ejecutar con debug activado en producción
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Definición de aplicaciones

INSTALLED_APPS = [
    'jazzmin',  # UI profesional para Django Admin (debe ir ANTES de django.contrib.admin)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Humanize para formatos legibles de números y fechas
    'calificaciones',  # Aplicación de calificaciones tributarias
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nuam_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nuam_project.wsgi.application'

# Base de datos
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Configuración de base de datos PostgreSQL

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

# Validación de contraseñas
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internacionalización
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Configuración de idioma y zona horaria para Chile

LANGUAGE_CODE = 'es-cl'

# Zona horaria de Santiago, Chile
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

USE_L10N = True

USE_THOUSAND_SEPARATOR = True

# Configuración de separadores numéricos
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'
NUMBER_GROUPING = 3

# Archivos estáticos (CSS, JavaScript, Imágenes)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Configuración de archivos estáticos

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Directorio donde se recopilan los archivos estáticos para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de archivos media (para cargas)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Redirección después del inicio de sesión
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'

# Tipo de campo de clave primaria por defecto
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================
# JAZZMIN CONFIGURATION
# ==============================
# Configuración del tema profesional para Django Admin
# Documentación: https://django-jazzmin.readthedocs.io/

JAZZMIN_SETTINGS = {
    # Títulos y branding
    "site_title": "NUAM Admin",
    "site_header": "NUAM Exchange",
    "site_brand": "NUAM Backoffice",
    "welcome_sign": "Bienvenido al Panel de Control Interno",
    "copyright": "NUAM Exchange",

    # Branding (descomentar si se agrega logo)
    # "site_logo": "img/logo_nuam.png", 
    
    # Personalización de UI
    "search_model": "calificaciones.CalificacionTributaria",
    
    # Menú superior
    "topmenu_links": [
        {"name": "Ir al Dashboard Público", "url": "home", "permissions": ["auth.view_user"]},
    ],

    # Menú de usuario
    "usermenu_links": [
        {"model": "auth.user"}
    ],
    
    # Menú lateral
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["calificaciones", "auth"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "calificaciones.CalificacionTributaria": "fas fa-file-invoice-dollar",
        "calificaciones.InstrumentoFinanciero": "fas fa-building",
        "calificaciones.ArchivoCargado": "fas fa-upload",
        "calificaciones.LogAuditoria": "fas fa-history",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # Tema limpio blanco/azul estilo corporativo
    # "theme": "lumen",  # Tema alternativo limpio
}
