# Generated by Django 5.2.8 on 2025-11-11 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(null=True, upload_to='cargas_masivas/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_exitosos', models.IntegerField(default=0)),
                ('registros_fallidos', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('EXITOSO', 'Exitoso'), ('PARCIAL', 'Parcial con errores'), ('FALLIDO', 'Fallido')], default='PROCESANDO', max_length=20)),
                ('errores_detalle', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cargas Masivas',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_instrumento', models.CharField(max_length=50, unique=True)),
                ('nombre_instrumento', models.CharField(max_length=255)),
                ('tipo_instrumento', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Instrumentos Financieros',
                'indexes': [models.Index(fields=['codigo_instrumento'], name='calificacio_codigo__a79698_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('READ', 'Consultar'), ('UPDATE', 'Modificar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión')], max_length=10)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.rol')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('factor', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('metodo_ingreso', models.CharField(choices=[('MONTO', 'Ingreso por Monto'), ('FACTOR', 'Ingreso por Factor')], default='MONTO', max_length=10)),
                ('numero_dj', models.CharField(blank=True, help_text='DJ 1949 o 1922', max_length=10)),
                ('fecha_informe', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.instrumentofinanciero')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones Tributarias',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_informe'], name='calificacio_fecha_i_01ec69_idx'), models.Index(fields=['numero_dj'], name='calificacio_numero__fa7553_idx')],
            },
        ),
    ]
