# Generated by Django 5.2 on 2025-11-14 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Actualizar campo 'accion' en LogAuditoria (aumentar max_length)
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(
                choices=[
                    ('CREATE', 'Crear'),
                    ('READ', 'Consultar'),
                    ('UPDATE', 'Modificar'),
                    ('DELETE', 'Eliminar'),
                    ('LOGIN', 'Inicio de sesión'),
                    ('LOGIN_FAILED', 'Intento de login fallido'),
                    ('LOGOUT', 'Cierre de sesión'),
                    ('ACCOUNT_LOCKED', 'Cuenta bloqueada'),
                ],
                max_length=20
            ),
        ),
        
        # 2. Crear modelo IntentoLogin
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('detalles', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Intentos de Login',
                'ordering': ['-fecha_hora'],
                'indexes': [
                    models.Index(fields=['username', 'fecha_hora'], name='calificacio_usernam_idx001'),
                    models.Index(fields=['ip_address', 'fecha_hora'], name='calificacio_ip_addr_idx002'),
                ],
            },
        ),
        
        # 3. Crear modelo CuentaBloqueada
        migrations.CreateModel(
            name='CuentaBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('fecha_desbloqueo', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueada', models.BooleanField(default=True)),
                ('razon', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cuentas Bloqueadas',
                'ordering': ['-fecha_bloqueo'],
            },
        ),
    ]
