# Generated by Django 5.2.8 on 2025-11-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_actualizacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intentologin',
            new_name='calificacio_usernam_a97897_idx',
            old_name='calificacio_usernam_idx001',
        ),
        migrations.RenameIndex(
            model_name='intentologin',
            new_name='calificacio_ip_addr_9fc5bb_idx',
            old_name='calificacio_ip_addr_idx002',
        ),
    ]
