# Generated by Django 5.2.8 on 2025-11-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_rename_calificacio_usernam_idx001_calificacio_usernam_a97897_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('READ', 'Consultar'), ('UPDATE', 'Modificar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Intento de login fallido'), ('LOGOUT', 'Cierre de sesión'), ('ACCOUNT_LOCKED', 'Cuenta bloqueada'), ('ACCOUNT_UNLOCKED', 'Cuenta desbloqueada')], max_length=20),
        ),
    ]
