# Generated by Django 5.2.8 on 2025-11-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_alter_logauditoria_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_10',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Factor 10'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_11',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Factor 11'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_12',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Factor 12'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_8',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Factor 8'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_9',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Factor 9'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='monto_10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Monto Factor 10'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='monto_11',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Monto Factor 11'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='monto_12',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Monto Factor 12'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='monto_8',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Con crédito por IDPC generados a contar del 01.01.2017', max_digits=18, null=True, verbose_name='Monto Factor 8'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='monto_9',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Con crédito por IDPC generados hasta el 31.12.2016', max_digits=18, null=True, verbose_name='Monto Factor 9'),
        ),
    ]
