# Generated by Django 5.2.8 on 2025-11-25 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_calificaciontributaria_factor_10_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('carga_masiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calificaciones.cargamasiva')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Archivos Cargados',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
