# Generated by Django 5.2.8 on 2025-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_archivocargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='calificaciontributaria',
            unique_together={('instrumento', 'fecha_informe', 'numero_dj')},
        ),
    ]
