# Generated by Django 5.2.8 on 2025-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_alter_calificaciontributaria_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='monto_10',
        ),
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='monto_11',
        ),
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='monto_12',
        ),
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='monto_8',
        ),
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='monto_9',
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_13',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 13'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_14',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 14'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_15',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 15'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_16',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 16'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_17',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 17'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_18',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 18'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_19',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 19'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_20',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 20'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_21',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 21'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_22',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 22'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_23',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 23'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_24',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 24'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_25',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 25'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_26',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 26'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_27',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 27'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_28',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 28'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_29',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 29'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_30',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 30'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_31',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 31'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_32',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 32'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_33',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 33'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_34',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 34'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_35',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 35'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_36',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 36'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_37',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 37'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_10',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 10'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_11',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 11'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_12',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 12'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_8',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 8'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor_9',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True, verbose_name='Factor 9'),
        ),
    ]
