# Generated by Django 5.2.8 on 2025-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0008_remove_calificaciontributaria_monto_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='numero_dividendo',
            field=models.IntegerField(blank=True, default=0, help_text='Número de dividendo asociado', null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='secuencia',
            field=models.IntegerField(blank=True, default=0, help_text='Número de secuencia del registro', null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='tipo_sociedad',
            field=models.CharField(blank=True, choices=[('A', 'Abierta'), ('C', 'Cerrada')], help_text='Tipo de sociedad: Abierta o Cerrada', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Valor histórico del instrumento', max_digits=18, null=True),
        ),
    ]
