# Generated by Django 5.2.8 on 2025-12-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0009_calificaciontributaria_numero_dividendo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='ejercicio',
            field=models.IntegerField(blank=True, default=0, help_text='Año de ejercicio tributario (4 dígitos)', null=True),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='mercado',
            field=models.CharField(blank=True, help_text='Código de mercado (ej: ACN, 3 chars)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='numero_dividendo',
            field=models.IntegerField(blank=True, default=0, help_text='Número de dividendo asociado (10 dígitos)', null=True),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='secuencia',
            field=models.IntegerField(blank=True, default=0, help_text='Número de secuencia del registro (10 dígitos)', null=True),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='tipo_sociedad',
            field=models.CharField(blank=True, choices=[('A', 'Abierta'), ('C', 'Cerrada')], help_text='Tipo de sociedad: A=Abierta, C=Cerrada', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Valor histórico del instrumento (10 dígitos)', max_digits=18, null=True),
        ),
    ]
