# Generated by Django 5.2.8 on 2025-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0010_calificaciontributaria_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentofinanciero',
            name='codigo_instrumento',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
