# Generated by Django 5.2.8 on 2025-12-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0011_alter_instrumentofinanciero_codigo_instrumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='origen',
            field=models.CharField(choices=[('BOLSA', 'Bolsa de Valores'), ('CORREDORA', 'Corredora de Bolsa'), ('MANUAL', 'Ingreso Manual')], default='MANUAL', help_text='Origen de los datos. CORREDORA tiene prioridad sobre BOLSA', max_length=10),
        ),
    ]
