# Generated by Django 5.2.8 on 2025-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0012_calificaciontributaria_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='fuente_origen',
            field=models.CharField(choices=[('MANUAL', 'Ingreso Manual'), ('MASIVA', 'Carga Masiva')], default='MANUAL', help_text='Método de entrada: Manual o Carga Masiva', max_length=20),
        ),
    ]
